services:
  backend:
    build:
      context: ./api-libreria
    ports:
      - "8000:80"
    volumes:
      - ./api-libreria:/var/www/html
    depends_on:
      - mysql

  frontend:
    build:
      context: ./frontend-libreria
    ports:
      - "3000:80"
    volumes:
      - ./frontend-libreria:/usr/share/nginx/html
    depends_on:
      - backend

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: biblioteca
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./api-libreria/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
